name: test_sketch

on: [push, pull_request]

jobs:
  test-matrix:
    strategy:
      matrix:
        arduino-platform: ["arduino:samd"]
        include:
          - arduino-platform: "arduino:samd"
            fqbn: "arduino:samd:nano_33_iot"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@master
      - name: Set up the Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
      - name: Compile the sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./ampel-main
