name: test_sketch

on: [push, pull_request]

jobs:
  test-matrix:
    strategy:
      matrix:
        arduino-platform: ["esp8266:esp8266"]
        include:
          - arduino-platform: "esp8266:esp8266"
            fqbn: "esp8266:esp8266:nodemcu"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@master
      - name: Set up the Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr@1.8.2
        
                
          arduino-cli core install ${{ matrix.arduino-platform }}
      - name: Compile the sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./ampel-main
